DROP EVENT IF EXISTS DELIVERED;
DROP PROCEDURE IF EXISTS P;

DELIMITER |
CREATE PROCEDURE P()
BEGIN
DECLARE DONE BOOLEAN DEFAULT FALSE;
DECLARE OIDL INTEGER;
DECLARE EIDL INTEGER;
DECLARE CUR CURSOR FOR SELECT OID FROM ORDERS WHERE DDATE=current_date();
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=TRUE;
OPEN CUR;
looop: LOOP
		FETCH CUR INTO OIDL;
        IF DONE THEN
			CLOSE CUR;
			LEAVE looop;
		ELSE
			UPDATE ORDERS SET OSTATUS='D' WHERE OID=OIDL;
			SELECT EID INTO EIDL FROM ORDERS WHERE OID=OIDL;
			UPDATE DELPPL SET ORDERCOUNT=ORDERCOUNT-1 WHERE EID=EIDL;
		END IF;
END LOOP looop;
END |

CREATE EVENT DELIVERED 
ON SCHEDULE EVERY 1 DAY
STARTS '2021-05-20 12:00:00'
ON COMPLETION PRESERVE
DO 
CALL P();