DROP EVENT IF EXISTS RETURNED;

DELIMITER |
CREATE EVENT RETURNED 
ON SCHEDULE EVERY 1 SECOND
STARTS CURRENT_TIMESTAMP
ON COMPLETION PRESERVE
DO 
BEGIN
DECLARE DONE BOOLEAN DEFAULT FALSE;
DECLARE OIDL INTEGER;
DECLARE RD DATE;
DECLARE CUR CURSOR FOR SELECT OID FROM ORDERS WHERE OSTATUS='D';
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=TRUE;
OPEN CUR;
looop: LOOP
		FETCH CUR INTO OIDL;
        IF DONE THEN
         CLOSE CUR;
         LEAVE looop;
		END IF;
        SELECT RDATE INTO RD FROM ORDERS WHERE OID=OIDL;
        IF DATE(NOW())>RD THEN
			UPDATE ORDERS SET FINE=DATEDIFF(current_date(),RD)*5 WHERE OID=OIDL;
		END IF;
END LOOP looop;
UPDATE ORDERS SET TOTAL=AMOUNT+FINE;
END |