DELIMITER |
CREATE TRIGGER DATES
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
DECLARE ORCOUNT INT;
SET ORCOUNT=(SELECT MIN(ORDERCOUNT) FROM DELPPL);
SET NEW.ODATE=DATE(NOW());
SET NEW.DDATE=(SELECT ADDDATE(DATE(NOW()), INTERVAL ORCOUNT+2 DAY));
SET NEW.RDATE=(SELECT ADDDATE(DATE(NOW()),INTERVAL 10 DAY));
END |